title: Reema Roy Blog
description: IT, websites, SEO, and growth — by Reema Roy.
url: "https://www.reemaroy.com"
baseurl: "/Reema-Roy"

permalink: /blog/:slug/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: "blog/_posts"
      type: posts
    values:
      layout: post
